repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-xml

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --recursive
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
          - --exclude
          - __init__.py
          - --remove-duplicate-keys

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--target-version=py312", "--line-length=140"]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py3-plus]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-async
          - flake8-comprehensions

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.3"
    hooks:
      - id: bandit
        args: ["-r", "--skip", "B324,B311,B110,B101,B113,B303,B304,B413,B107"]
        exclude: "scripts/migrations.py"


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/AliYmn/conventional-commits-check
    rev: v2.9.0
    hooks:
      - id: conventional-commits-check
        stages: [commit-msg]
        args: ["--emoji-disabled"]

  # - repo: https://github.com/twu/skjold
  #   rev: "v0.6.2"
  #   hooks:
  #     - id: skjold
  #       verbose: true
  #       args: ["-s", "pyup"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        args:
          [
            --output-format=colorized,
            --disable=all,
            --enable=W0611,W0612,W0621,R1705,E0102,E0602,E0401
          ]
        exclude: 'utils/migrations/versions/'
        stages: [manual] # TODO: remove this
